#! /usr/bin/env python

import os
import sys

if len(sys.argv) >= 3 and sys.argv[1] == "-l":
  username = sys.argv[2] + "@"
  del sys.argv[1:3]
else:
  username = ""

if len(sys.argv) < 2 or sys.argv[1] not in ["push", "pull", "incoming",
  "outgoing", "clone"]:
  sys.stderr.write(
"""Usage: badger [-l username] push|pull|incoming|outgoing|clone [hgopts]

Performs an operation between the local repository and its remote
counterpart on badger.  Do not specify the location of the remote
repository--- that's what this script is for.  The -l option can be
used to specify an alternate username for logging in to badger
(generally necessary if currently logged in as the role account).
""")
  sys.exit(1)

os.execvp("hg", ["hg"] + sys.argv[1:] + ["--remotecmd", "/tdr/bin/hg",
  "ssh://%sbadger.cdlib.org//tdr/hg/ezid" % username])
