# Upgrade EZID Deployment

Describes the process for replacing an exising EZID instance with 
a parallel deployment of the upgrade instance.

[NOTE]
This document targets the late 2020 upgrade of EZID for support of
local minting instead of reliance on N2T. Subsequent upgrades may differ in
some details.

The process outlined here uses a parallel installation of the EZID 
application on a different EC2 instance to the existing EZID instance. 
The outcome of the process is a new instance of EZID initiated with 
data from the original installation.

The following definitions apply here:

`VM-1`:: Virtual machine (i.e. EC2 instance) hosting the existing installation
of the EZID application.
`EZID-1`:: Existing instance of the EZID application running on `VM-1`
`DB-1`:: Existing RDS database instance holding the data for `EZID-1`
`VM-2`:: The new virtual machine (EC2 instance) that will be hosting the new
instance of the EZID application
`EZID-2`:: The new instance of the EZID application to be running on `VM-2`
`DB-2`:: The new RDS database instance used by `EZID-2`

## Preparation

### Base Installation

1. Create a new EC2 instance (`VM-2`) to host the new EZID instance 
(`EZID-2`).
2. Run the Ansible and Puppet scripts to perform the base installation.

The outcome of these steps is an EC2 instance with the EZID application
and associated configuration located under `/apps/ezid`.

The folder layout looks like:

[source]
----
.
├── .profile.d      # <1>
├── .pyenv          # <2>
├── bin
├── download -> /apps/ezid/var/www/download
├── etc
│   ├── httpd
│   └── init.d
├── ezid            # <3>
│   ├── settings
│   ├── tools
│   ...
├── install
│   └── ezid-ansible
├── logs -> /apps/ezid/var/log/ezid
└── var
    ├── log
    ├── minters
    ├── run
    └── www
----
<1> Environment variables
<2> Python virtual environment
<3> Location of the new EZID application, `EZID-2`


Manual configuration and operation of the EZID application is achieved by
logging in to `VM-2` and becomming the `ezid` user by:

[source, bash]
----
sudo su - ezid
----

Environment variables for the user are set by `~/.profile.d/ezid`:

[source, bash]
----
if [ -d "$HOME"/.pyenv ]; then
  export PYENV_ROOT="$HOME/.pyenv"                 #<1>
  export PATH="$PYENV_ROOT/bin:$PATH"
  eval "$(pyenv init -)"
  eval "$(pyenv virtualenv-init -)"
fi
export DJANGO_SETTINGS_MODULE=settings.remotedev   #<2>
----
<1> The application uses a Python virtual environment rather than the system Python
installation. The Python virtual environment is located under `~/.pyenv` and
additional Python dependencies (if needed) should be installed using `pip` as the
`ezid` user.
<2> The `DJANGO_SETTINGS_MODULE` will need to be set according to
the environment being deployed (e.g. `settings.production` for the production
environment). The value refers to the python settings module within the EZID
application, and corresponds with the file location `~/ezid/settings/`.


### Application Configuration


#### ~/etc/ezid_env.sh and ~/.profile.d/ezid

Sets up the python virtual environment for the EZID application.

`DJANGO_SETTINGS_MODULE` determines which settings are loaded for
the application:

Production environment:: `settings.production`
Stage2 environment:: `settings.remotedev`
Dev environment:: `settings.remotedev`

The `settings.*` files override common settings in `settings/common.py`

The settings files load configuration information from `settings/ezid.conf`
and `settings/ezid.conf.shadow`, with the latter holding passwords.

In the following, substitute `{production}` for the name of the environment
being deployed (e.g. `{remotedev}` for a development environment).

#### Edit File: `~/ezid/settings/common.py`

Run:

[source, bash]
----
mkdir -p /apps/ezid/var/minters
chmod ug+s /apps/ezid/var/minters
----

and update minters path to:
----
MINTERS_PATH = '/apps/ezid/var/minters'
----

#### Edit File: `~/ezid/settings/ezid.conf`

----
[DEFAULT]
{production}ezid_base_url: https://uc3-ezid-ui-prd.cdlib.org      <1>

[auth]
admin_username: admin                                             <2>

[email]
{production}new_account_email: jak@ucop.edu,maria.gould@ucop.edu  <3>

[shoulders]
{production}url: file:///apps/ezid/ezid/master_shoulders.txt      <4>

[cloudwatch]
{production}instance_name: uc3-ezidx2-prd                         <5>

[datacite]                                                        <6>

[crossref]                                                        <7>

----
<1> *Set* to the external URL that will be used to access EZID
<2> Verify this is the expected value for the administrator username
<3> Verify email address entries for new account requests
<4> *Set* the absolute file URL for the location of the
    `master_shoulders.txt` file
<5> Verify the correct value for the cloudwatch service
<6> Verify entries for DataCite configuration
<7> Verify entries for Crossref configuration

#### Edit File: `~/ezid/settings/ezid.conf.shadow`

----
[auth]
admin_password:
{production}admin_password: ****                                  <1>

[databases]
store_host: ****                                                  <2>
store_port: 3306
store_password: ****                                              <3>
search_host: ****                                                 <4>
search_port: 3306
search_password: ****                                             <5>
----
<1> *Add* line `{production}admin_password:` and set the password for the administrator (EZID admin) account
<2> *Set* the RDS host for `DB-2`
<3> *Set* the RDS password for `DB-2`
<4> *Set* to same as `store_host`
<5> *Set* to same as `store_password`

#### Edit file: `~/ezid/settings/production.py` and change `ALLOWED_HOSTS` to:
----
ALLOWED_HOSTS = ['*']
----

#### Run `hostname` in the shell and add the output to the list at `impl/nog/reload.py`

----
KNOWN_EZID_HOSTNAME_TUP = (
    <The new hostname goes here. E.g., 'uc3-ezidui01x2-prd'>,
    ...
----

Verify correct setup for automatic reload
----
$ ./manage.py diag-reload
----
It should return `success: configuration file reloaded and caches emptied`.


## Dry-Run Upgrade

This procedure will step through the upgrade process but will not 
replace the existing EZID instance.

Prerequisite: The steps in "Preparation/Base Installation" and
"Preparation/Application Configuration" have been completed.

In the following `ad-1` refers to an administrator for `EZID-1`, and
`ad-2` refers to an administrator for `EZID-2`. They may be the same person.

[cols="1,2,15", options="header"]
|===
|# |Who |Action
|1
|`ad-1`
|Set the offline notice for `EZID-1`
|2
|`ad-2`
a|Shut down `EZID-2` if it is running

----
~/etc/init.d/httpd stop
----

|3
|IAS
|Clone `DB-1` to create / overwrite `DB-2`

|4
|`ad-1`
|Unset the offline notice for `EZID-1`. *Note:* this step
is not done when doing an actual upgrade.

|5
|`ad-2`
|Get the most recent copy of `master_shoulders.txt` and
place in `~/ezid/master_shoulders.txt`

|6
|`ad-2`
|Verify database settings

|7
|`ad-2`
a|Upgrade the database schema:

----
./manage.py migrate
----

|8
|`ad-2`
a|Check minters:

----
./manage.py  shoulder-check-minters
----

|9
|`ad-2`
a|Merge Shoulders

----
./manage.py shoulder-merge-master
----

|10
|`ad-2`
a|Startup `EZID-2`

----
~/etc/init.d/httpd start
----

|11
|all
|Verify `EZID-2` running as expected.

|===


## Upgrade

## Cleanup
