---

## Configure the EZID application

- name: symlink ezid logs
  file:
    path: "{{ app_dir }}/logs"
    src: "{{ app_dir }}/var/log/ezid"
    state: link
- name: symlink download dir
  file:
    path: "{{ app_dir }}/download"
    src: "{{ app_dir }}/var/www/download"
    state: link

- name: settings.py
  template:
    #src: "{{ app_dir }}/ezid/settings/settings_template.py"
    src: "templates/ezid/settings/settings.py.j2"
    dest: "{{ app_dir }}/ezid/settings/settings.py"
    owner: "{{ user }}"
    group: "{{ group }}"
    mode: "0600"

- name: run setup.py
  ansible.builtin.command:
    chdir: "{{ app_dir }}/ezid"
    argv:
      - "{{ pyenv_root }}/versions/{{ pyenv_global }}/bin/python"
      - "{{ app_dir }}/ezid/setup.py"
      - develop
  register: _response

- name: run pyenv rehash
  ansible.builtin.command: pyenv rehash

#- when: _response.rc is defined
#  block:
#
#  - name: report setup.py response std_out
#    debug:
#      msg="{{ _response.stdout_lines }}"
#  
#  - name: report setup.py response std_err
#    debug:
#      msg="{{ _response.stderr_lines }}"

