---

## Configure the EZID application

- name: symlink ezid logs
  file:
    path: "{{ app_dir }}/logs"
    src: "{{ app_dir }}/var/log/ezid"
    state: link
- name: symlink download dir
  file:
    path: "{{ app_dir }}/download"
    src: "{{ app_dir }}/var/www/download"
    state: link

- name: settings.py
  template:
    #src: "templates/ezid/settings/settings.py.j2"
    src: "{{ app_dir }}/ezid/settings/settings_template.py"
    dest: "{{ app_dir }}/ezid/settings/settings.py"
    owner: "{{ user }}"
    group: "{{ group }}"
    mode: "0600"

- name: run setup.py
  ansible.builtin.command:
    chdir: "{{ app_dir }}/ezid"
    argv:
      - "{{ app_dir }}/ezid/setup.py"
      - develop
  register: _response

- when: _response.rc is defined
  block:
  - name: report setup.py response std_out
    debug:
      msg="{{ _response.stdout_lines }}"
  
  - name: report setup.py response std_err
    debug:
      msg="{{ _response.stderr_lines }}"

    # - name: install ezid requirements
    #   pip:
    #     requirements: "{{ app_dir }}/ezid/requirements.txt"
    #     executable: "{{ pyenv_root }}/versions/{{ pyenv_global }}/bin/pip"

    #- name: discover path to mod_wsgi shared object file
    #  shell: "find {{ site_packages.stdout }} -name \"mod_wsgi*.so\""
    #  register: mod_wsgi_so
    #
    #- name: report mod_wsgi shared object filename
    #  ansible.builtin.debug: msg="{{ mod_wsgi_so.stdout }}"
