---

- name: symlink to system httpd modules
  file:
    path: "{{ app_dir }}/etc/httpd/modules"
    src: "/etc/httpd/modules"
    state: link
- name: symlink to system httpd magic
  file:
    path: "{{ app_dir }}/etc/httpd/conf/magic"
    src: "/etc/httpd/conf/magic"
    state: link

- name: httpd.conf
  template:
    src: "templates/etc/httpd/conf/httpd.conf.j2"
    dest: "{{ app_dir }}/etc/httpd/conf/httpd.conf"
    owner: "{{user}}"
    group: "{{group}}"
    mode: "0644"

- name: httpd/conf.d/01-ezid-ssl.conf
  template:
    src: "templates/etc/httpd/conf.d/01-ezid-ssl.conf.j2"
    dest: "{{ app_dir }}/etc/httpd/conf.d/01-ezid-ssl.conf"
    owner: "{{user}}"
    group: "{{group}}"
    mode: "0644"
  when: use_ssl

- name: httpd/conf.d/02-wsgi.conf
  template:
    src: "templates/etc/httpd/conf.d/02-wsgi.conf.j2"
    dest: "{{ app_dir }}/etc/httpd/conf.d/02-wsgi.conf"
    owner: "{{user}}"
    group: "{{group}}"
    mode: "0644"
- name: httpd/conf.d/03-ezid-nossl.conf
  template:
    src: "templates/etc/httpd/conf.d/03-ezid-nossl.conf.j2"
    dest: "{{ app_dir }}/etc/httpd/conf.d/03-ezid-nossl.conf"
    owner: "{{user}}"
    group: "{{group}}"
    mode: "0644"

- name: httpd/conf.modules.d/00-mpm.conf
  template:
    src: "templates/etc/httpd/conf.modules.d/00-mpm.conf.j2"
    dest: "{{ app_dir }}/etc/httpd/conf.modules.d/00-mpm.conf"
    owner: "{{user}}"
    group: "{{group}}"
    mode: "0644"
- name: httpd/conf.modules.d/01-wsgi.conf
  template:
    src: "templates/etc/httpd/conf.modules.d/01-wsgi.conf.j2"
    dest: "{{ app_dir }}/etc/httpd/conf.modules.d/01-wsgi.conf"
    owner: "{{user}}"
    group: "{{group}}"
    mode: "0644"
- name: httpd/conf.modules.d/*
  copy:
    src: "files/etc/httpd/conf.modules.d/"
    dest: "{{ app_dir }}/etc/httpd/conf.modules.d/"
    owner: "{{user}}"
    group: "{{group}}"
    mode: "0644"

- name: robots.txt
  copy:
    src: "files/var/www/html/robots.txt"
    dest: "{{ app_dir }}/var/www/html/"
    owner: "{{user}}"
    group: "{{group}}"
    mode: "0644"
