---

- name: etc/init.d/pause_ezid.sh
  template:
    src: "templates/etc/init.d/pause_ezid.sh.j2"
    dest: "{{app_dir}}/etc/init.d/pause_ezid.sh"
    owner: "{{user}}"
    group: "{{group}}"
    mode: "0775"
- name: bin/exercise_ezid.sh
  template:
    src: "templates/bin/exercise_ezid.sh.j2"
    dest: "{{app_dir}}/bin/exercise_ezid.sh"
    owner: "{{user}}"
    group: "{{group}}"
    mode: "0775"
