---

- name: Clone ezid repo
  git:
    repo: "{{ ezid_repo }}"
    dest: "{{ app_dir }}/ezid/"
    version: "{{ ezid_branch }}"
    force: yes
- name: install ezid requirements
  pip:
    requirements: "{{ app_dir }}/ezid/requirements.txt"
    executable: "{{ pyenv_root }}/versions/{{ pyenv_global }}/bin/pip"
- name: install wheel
  pip:
    name: wheel
    executable: "{{ pyenv_root }}/versions/{{ pyenv_global }}/bin/pip"
- name: Clone ezid-info-pages repo
  git:
    repo: "{{ ezid_info_pages_repo }}"
    dest: "{{ app_dir }}/ezid/templates/info/"
    version: "{{ ezid_info_pages_branch }}"
