---

- name: "Create application directory trees"
  # shell:RUN mkdir -p etc/{httpd/{conf,conf.d,conf.modules.d},init.d} var/{run,log/{httpd,ezid},www/{html,download/{public}}}; \
  file:
    path: "{{item}}"
    owner: "{{user}}"
    group: "{{group}}"
    state: directory
    recurse: yes
  with_items:
  - "{{app_dir}}/bin"
  - "{{app_dir}}/etc/httpd/conf"
  - "{{app_dir}}/etc/httpd/conf.d"
  - "{{app_dir}}/etc/httpd/modules.d"
  - "{{app_dir}}/etc/init.d"
  - "{{app_dir}}/var/run"
  - "{{app_dir}}/var/log/ezid"
  - "{{app_dir}}/var/log/httpd"
  - "{{app_dir}}/var/www/html"
  - "{{app_dir}}/var/www/download/public"
- name: symlink httpd modules
  # ln -s /etc/httpd/modules /apps/ezid/etc/httpd/modules; \
  file:
    path: "{{app_dir}}/etc/httpd/modules"
    src: "/etc/httpd/modules"
    state: link
- name: symlink ezid logs
  # ln -s /apps/ezid/var/log/ezid /apps/ezid/logs; \
  file:
    path: "{{app_dir}}/logs"
    src: "{{app_dir}}/var/log/ezid"
    state: link

- name: ~/.bash_profile
  copy:
    src: files/.bash_profile
    dest: "{{ansible_env.HOME}}/.bash_profile"
    owner: "{{user}}"
    group: "{{group}}"
    mode: "0644"
- name: ~/.bashrc
  copy:
    src: files/.bashrc
    dest: "{{ansible_env.HOME}}/.bashrc"
    owner: "{{user}}"
    group: "{{group}}"
    mode: "0644"
    force: no
- name: ~/.alias
  copy:
    src: files/.alias
    dest: "{{ansible_env.HOME}}/.alias"
    owner: "{{user}}"
    group: "{{group}}"
    mode: "0644"
    force: no
- name: mkdir ~/.profile.d
  file:
    path: "{{ansible_env.HOME}}/.profile.d"
    owner: "{{user}}"
    group: "{{group}}"
    state: directory
- name: update ~/.profile.d/pyenv
  blockinfile:
    path: "{{ansible_env.HOME}}/.profile.d/pyenv"
    create: yes
    owner: "{{user}}"
    group: "{{group}}"
    block: |
      #
      # pyenv setup
      #
      if [ -d "$HOME"/.pyenv ]; then
        export PYENV_ROOT="$HOME/.pyenv"
        export PATH="$PYENV_ROOT/bin:$PATH"
        eval "$(pyenv init -)"
        eval "$(pyenv virtualenv-init -)"
      fi


- name: setup pyenv 
  # from https://galaxy.ansible.com/suzuki-shunsuke/pyenv-module
  pyenv:
    version: "{{pyver}}"
    pyenv_root: "{{pyenv_root}}"
    #subcommand: uninstall
  environment:
    CONFIGURE_OPTS: "--enable-shared"
    CFLAGS: "-O2"
- name: pyenv virtualenv
  pyenv:
    subcommand: virtualenv
    version: "{{pyver}}"
    pyenv_root: "{{pyenv_root}}"
    virtualenv_name: "{{venv_name}}"
- name: pyenv global
  pyenv:
    subcommand: global
    versions:
    - "{{venv_name}}"
    pyenv_root: "{{pyenv_root}}"
- name: install python packages on the virtualenv
  pip:
    name: ['mod_wsgi']
    #name: ['mysqlclient', 'mod_wsgi']
    executable: "{{pyenv_root}}/versions/{{venv_name}}/bin/pip"

