# Generated by Django 3.2.10 on 2022-10-26 11:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ezidapp', '0001_initial'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='identifier',
            index=models.Index(fields=['createTime'], name='ezidapp_ide_createT_439579_idx'),
        ),
        migrations.AddIndex(
            model_name='identifier',
            index=models.Index(fields=['updateTime'], name='ezidapp_ide_updateT_88212d_idx'),
        ),
        migrations.AddIndex(
            model_name='searchidentifier',
            index=models.Index(fields=['createTime'], name='ezidapp_sea_createT_0c4dda_idx'),
        ),
        migrations.AddIndex(
            model_name='searchidentifier',
            index=models.Index(fields=['updateTime'], name='ezidapp_sea_updateT_60feca_idx'),
        ),
    ]
