# Generated by Django 3.2.18 on 2023-07-13 17:35

import django.core.validators
from django.db import migrations, models
import re


class Migration(migrations.Migration):

    dependencies = [
        ('ezidapp', '0003_auto_20230713_1643'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProfileCopy',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.CharField(max_length=32, unique=True, validators=[django.core.validators.RegexValidator('^[a-z0-9]+([-_.][a-z0-9]+)*$', 'Invalid profile name.', flags=re.RegexFlag['IGNORECASE'])])),
            ],
        ),
    ]
