# Generated by Django 3.2.17 on 2023-07-18 09:56

import django.core.serializers.json
import django.core.validators
from django.db import migrations, models
import ezidapp.models.validation


class Migration(migrations.Migration):

    dependencies = [
        ('ezidapp', '0003_auto_20230718_0955'),
    ]

    operations = [
        migrations.CreateModel(
            name='Minter',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('prefix', models.CharField(max_length=255, unique=True, validators=[ezidapp.models.validation.shoulder])),
                ('minterState', models.JSONField(default=dict, encoder=django.core.serializers.json.DjangoJSONEncoder)),
                ('createTime', models.IntegerField(blank=True, db_index=True, default='', validators=[django.core.validators.MinValueValidator(0)])),
                ('updateTime', models.IntegerField(blank=True, db_index=True, default='', validators=[django.core.validators.MinValueValidator(0)])),
            ],
        ),
    ]
