# Generated by Django 3.2.18 on 2023-07-13 17:55

from django.db import migrations, models
import ezidapp.models.validation


class Migration(migrations.Migration):

    dependencies = [
        ('ezidapp', '0004_profilecopy'),
    ]

    operations = [
        migrations.AddField(
            model_name='profilecopy',
            name='prefix',
            field=models.CharField(default='ark:/99999/fk8', max_length=255, unique=True, validators=[ezidapp.models.validation.shoulder]),
        ),
    ]
