# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2020-07-27 00:35


import django.db.migrations
import django.db.models.deletion


class Migration(django.db.migrations.Migration):

    dependencies = [
        ('ezidapp', '0024_downloadqueue_filesize'),
    ]

    operations = [
        django.db.migrations.CreateModel(
            name='ShoulderType',
            fields=[
                (
                    'id',
                    django.db.models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name='ID',
                    ),
                ),
                (
                    'shoulder_type',
                    django.db.models.CharField(editable=False, max_length=32),
                ),
            ],
        ),
        django.db.migrations.AddField(
            model_name='shoulder',
            name='active',
            field=django.db.models.BooleanField(default=False, editable=False),
        ),
        django.db.migrations.AddField(
            model_name='shoulder',
            name='date',
            field=django.db.models.DateField(blank=True, editable=False, null=True),
        ),
        django.db.migrations.AddField(
            model_name='shoulder',
            name='isSupershoulder',
            field=django.db.models.BooleanField(default=False, editable=False),
        ),
        django.db.migrations.AddField(
            model_name='shoulder',
            name='manager',
            field=django.db.models.CharField(
                blank=True, editable=False, max_length=32, null=True
            ),
        ),
        django.db.migrations.AddField(
            model_name='shoulder',
            name='prefix_shares_datacenter',
            field=django.db.models.BooleanField(default=False, editable=False),
        ),
        django.db.migrations.AddField(
            model_name='shoulder',
            name='redirect',
            field=django.db.models.URLField(
                blank=True, editable=False, max_length=255, null=True
            ),
        ),
        django.db.migrations.AddField(
            model_name='shoulder',
            name='shoulder_type',
            field=django.db.models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to='ezidapp.ShoulderType',
            ),
        ),
    ]
