# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2020-07-28 20:41


from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ezidapp', '0025_auto_20200727_0035'),
    ]

    operations = [
        migrations.CreateModel(
            name='RegistrationAgency',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('registration_agency', models.CharField(editable=False, max_length=32)),
            ],
        ),
        migrations.AddField(
            model_name='shoulder',
            name='registration_agency',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='ezidapp.RegistrationAgency'),
        ),
    ]
