# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2020-07-28 20:41


import django.db.migrations
import django.db.models.deletion


class Migration(django.db.migrations.Migration):

    dependencies = [
        ('ezidapp', '0025_auto_20200727_0035'),
    ]

    operations = [
        django.db.migrations.CreateModel(
            name='RegistrationAgency',
            fields=[
                (
                    'id',
                    django.db.models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name='ID',
                    ),
                ),
                (
                    'registration_agency',
                    django.db.models.CharField(editable=False, max_length=32),
                ),
            ],
        ),
        django.db.migrations.AddField(
            model_name='shoulder',
            name='registration_agency',
            field=django.db.models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to='ezidapp.RegistrationAgency',
            ),
        ),
    ]
