# Generated by Django 3.1.7 on 2021-02-24 05:22

import datetime

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models

import ezidapp.models.validation


class Migration(migrations.Migration):

    dependencies = [
        ('ezidapp', '0026_auto_20200728_2041'),
    ]

    operations = [
        migrations.AlterField(
            model_name='binderqueue',
            name='operation',
            field=models.CharField(
                choices=[('C', 'create'), ('U', 'update'), ('D', 'delete')],
                max_length=1,
            ),
        ),
        migrations.AlterField(
            model_name='crossrefqueue',
            name='operation',
            field=models.CharField(
                choices=[('C', 'create'), ('U', 'update'), ('D', 'delete')],
                max_length=1,
            ),
        ),
        migrations.AlterField(
            model_name='crossrefqueue',
            name='status',
            field=models.CharField(
                choices=[
                    ('U', 'awaiting submission'),
                    ('S', 'submitted'),
                    ('W', 'registered with warning'),
                    ('F', 'registration failed'),
                ],
                db_index=True,
                default='U',
                max_length=1,
            ),
        ),
        migrations.AlterField(
            model_name='datacitequeue',
            name='operation',
            field=models.CharField(
                choices=[('C', 'create'), ('U', 'update'), ('D', 'delete')],
                max_length=1,
            ),
        ),
        migrations.AlterField(
            model_name='downloadqueue',
            name='compression',
            field=models.CharField(choices=[('G', 'GZIP'), ('Z', 'ZIP')], max_length=1),
        ),
        migrations.AlterField(
            model_name='downloadqueue',
            name='format',
            field=models.CharField(
                choices=[('A', 'ANVL'), ('C', 'CSV'), ('X', 'XML')], max_length=1
            ),
        ),
        migrations.AlterField(
            model_name='downloadqueue',
            name='stage',
            field=models.CharField(
                choices=[
                    ('C', 'create'),
                    ('H', 'harvest'),
                    ('Z', 'compress'),
                    ('D', 'delete'),
                    ('M', 'move'),
                    ('N', 'notify'),
                ],
                default='C',
                max_length=1,
            ),
        ),
        migrations.AlterField(
            model_name='newaccountworksheet',
            name='accountEmail',
            field=models.EmailField(
                blank=True,
                help_text="Defaults to the primary contact's email.",
                max_length=255,
                verbose_name='account email',
            ),
        ),
        migrations.AlterField(
            model_name='newaccountworksheet',
            name='orgAcronym',
            field=models.CharField(
                blank=True, help_text='Ex: tDAR', max_length=255, verbose_name='acronym'
            ),
        ),
        migrations.AlterField(
            model_name='newaccountworksheet',
            name='orgName',
            field=models.CharField(
                help_text='Ex: The Digital Archaeological Record',
                max_length=255,
                validators=[ezidapp.models.validation.nonEmpty],
                verbose_name='name',
            ),
        ),
        migrations.AlterField(
            model_name='newaccountworksheet',
            name='orgStreetAddress',
            field=models.CharField(
                blank=True, max_length=255, verbose_name='street address'
            ),
        ),
        migrations.AlterField(
            model_name='newaccountworksheet',
            name='orgUrl',
            field=models.URLField(blank=True, max_length=255, verbose_name='URL'),
        ),
        migrations.AlterField(
            model_name='newaccountworksheet',
            name='priEmail',
            field=models.EmailField(blank=True, max_length=255, verbose_name='email'),
        ),
        migrations.AlterField(
            model_name='newaccountworksheet',
            name='priName',
            field=models.CharField(blank=True, max_length=255, verbose_name='name'),
        ),
        migrations.AlterField(
            model_name='newaccountworksheet',
            name='priPhone',
            field=models.CharField(blank=True, max_length=255, verbose_name='phone'),
        ),
        migrations.AlterField(
            model_name='newaccountworksheet',
            name='reqArks',
            field=models.BooleanField(default=False, verbose_name='ARKs'),
        ),
        migrations.AlterField(
            model_name='newaccountworksheet',
            name='reqComments',
            field=models.TextField(blank=True, verbose_name='requestor comments'),
        ),
        migrations.AlterField(
            model_name='newaccountworksheet',
            name='reqCrossref',
            field=models.BooleanField(default=False, verbose_name='Crossref'),
        ),
        migrations.AlterField(
            model_name='newaccountworksheet',
            name='reqCrossrefEmail',
            field=models.EmailField(
                blank=True, max_length=255, verbose_name='Crossref email'
            ),
        ),
        migrations.AlterField(
            model_name='newaccountworksheet',
            name='reqDois',
            field=models.BooleanField(default=False, verbose_name='DOIs'),
        ),
        migrations.AlterField(
            model_name='newaccountworksheet',
            name='reqEmail',
            field=models.EmailField(blank=True, max_length=255, verbose_name='email'),
        ),
        migrations.AlterField(
            model_name='newaccountworksheet',
            name='reqName',
            field=models.CharField(blank=True, max_length=255, verbose_name='name'),
        ),
        migrations.AlterField(
            model_name='newaccountworksheet',
            name='reqPhone',
            field=models.CharField(blank=True, max_length=255, verbose_name='phone'),
        ),
        migrations.AlterField(
            model_name='newaccountworksheet',
            name='requestDate',
            field=models.DateField(
                default=datetime.date.today, verbose_name='request date'
            ),
        ),
        migrations.AlterField(
            model_name='newaccountworksheet',
            name='secEmail',
            field=models.EmailField(blank=True, max_length=255, verbose_name='email'),
        ),
        migrations.AlterField(
            model_name='newaccountworksheet',
            name='secName',
            field=models.CharField(blank=True, max_length=255, verbose_name='name'),
        ),
        migrations.AlterField(
            model_name='newaccountworksheet',
            name='secPhone',
            field=models.CharField(blank=True, max_length=255, verbose_name='phone'),
        ),
        migrations.AlterField(
            model_name='newaccountworksheet',
            name='setGroupname',
            field=models.CharField(
                blank=True, max_length=255, verbose_name='groupname'
            ),
        ),
        migrations.AlterField(
            model_name='newaccountworksheet',
            name='setNonDefaultSetup',
            field=models.BooleanField(default=False, verbose_name='non-default setup'),
        ),
        migrations.AlterField(
            model_name='newaccountworksheet',
            name='setNotes',
            field=models.TextField(blank=True, verbose_name='notes'),
        ),
        migrations.AlterField(
            model_name='newaccountworksheet',
            name='setRealm',
            field=models.CharField(blank=True, max_length=255, verbose_name='realm'),
        ),
        migrations.AlterField(
            model_name='newaccountworksheet',
            name='setShoulderDisplayName',
            field=models.CharField(
                blank=True,
                help_text='Defaults to the organization name.',
                max_length=255,
                verbose_name='shoulder display name',
            ),
        ),
        migrations.AlterField(
            model_name='newaccountworksheet',
            name='setUserDisplayName',
            field=models.CharField(
                blank=True,
                help_text='Defaults to the organization name.',
                max_length=255,
                verbose_name='user display name',
            ),
        ),
        migrations.AlterField(
            model_name='newaccountworksheet',
            name='setUsername',
            field=models.CharField(blank=True, max_length=255, verbose_name='username'),
        ),
        migrations.AlterField(
            model_name='newaccountworksheet',
            name='staAccountCreated',
            field=models.BooleanField(default=False, verbose_name='account created'),
        ),
        migrations.AlterField(
            model_name='newaccountworksheet',
            name='staReady',
            field=models.BooleanField(default=False, verbose_name='request ready'),
        ),
        migrations.AlterField(
            model_name='newaccountworksheet',
            name='staShouldersCreated',
            field=models.BooleanField(default=False, verbose_name='shoulders created'),
        ),
        migrations.AlterField(
            model_name='searchidentifier',
            name='agentRole',
            field=models.CharField(
                blank=True,
                choices=[('U', 'user'), ('G', 'group')],
                default='',
                max_length=1,
            ),
        ),
        migrations.AlterField(
            model_name='searchidentifier',
            name='createTime',
            field=models.IntegerField(
                blank=True,
                default='',
                validators=[django.core.validators.MinValueValidator(0)],
            ),
        ),
        migrations.AlterField(
            model_name='searchidentifier',
            name='crossrefMessage',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='searchidentifier',
            name='crossrefStatus',
            field=models.CharField(
                blank=True,
                choices=[
                    ('R', 'awaiting status change to public'),
                    ('B', 'registration in progress'),
                    ('S', 'successfully registered'),
                    ('W', 'registered with warning'),
                    ('F', 'registration failure'),
                ],
                default='',
                max_length=1,
            ),
        ),
        migrations.AlterField(
            model_name='searchidentifier',
            name='searchableResourceType',
            field=models.CharField(
                choices=[
                    ('A', 'Audiovisual'),
                    ('C', 'Collection'),
                    ('D', 'Dataset'),
                    ('E', 'Event'),
                    ('Im', 'Image'),
                    ('In', 'InteractiveResource'),
                    ('M', 'Model'),
                    ('Z', 'Other'),
                    ('P', 'PhysicalObject'),
                    ('Se', 'Service'),
                    ('So', 'Software'),
                    ('Su', 'Sound'),
                    ('T', 'Text'),
                    ('W', 'Workflow'),
                ],
                editable=False,
                max_length=2,
            ),
        ),
        migrations.AlterField(
            model_name='searchidentifier',
            name='status',
            field=models.CharField(
                choices=[('R', 'reserved'), ('P', 'public'), ('U', 'unavailable')],
                default='P',
                max_length=1,
            ),
        ),
        migrations.AlterField(
            model_name='searchidentifier',
            name='target',
            field=models.URLField(
                blank=True,
                default='',
                max_length=2000,
                validators=[ezidapp.models.validation.unicodeBmpOnly],
            ),
        ),
        migrations.AlterField(
            model_name='searchidentifier',
            name='unavailableReason',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='searchidentifier',
            name='updateTime',
            field=models.IntegerField(
                blank=True,
                default='',
                validators=[django.core.validators.MinValueValidator(0)],
            ),
        ),
        migrations.AlterField(
            model_name='servervariables',
            name='alertMessage',
            field=models.CharField(
                blank=True,
                help_text='The alert message can be used to communicate urgent announcements.  It is displayed at the top of every UI page.',
                max_length=255,
                verbose_name='alert message',
            ),
        ),
        migrations.AlterField(
            model_name='servervariables',
            name='secretKey',
            field=models.CharField(
                blank=True,
                help_text='The secret key identifies the server; changing it invalidates every API session cookie, password reset URL, and OAI-PMH resumption token.  Set it to blank to generate a new random key.',
                max_length=50,
                verbose_name='secret key',
            ),
        ),
        migrations.AlterField(
            model_name='shoulder',
            name='crossrefEnabled',
            field=models.BooleanField(default=False, verbose_name='Crossref enabled'),
        ),
        migrations.AlterField(
            model_name='shoulder',
            name='registration_agency',
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                to='ezidapp.registrationagency',
            ),
        ),
        migrations.AlterField(
            model_name='shoulder',
            name='shoulder_type',
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                to='ezidapp.shouldertype',
            ),
        ),
        migrations.AlterField(
            model_name='storegroup',
            name='accountType',
            field=models.CharField(
                blank=True,
                choices=[
                    ('B', 'Associate/bachelors-granting'),
                    ('C', 'Corporate'),
                    ('G', 'Group'),
                    ('I', 'Institution'),
                    ('M', 'Masters-granting'),
                    ('N', 'Non-paying'),
                    ('S', 'Service'),
                ],
                max_length=1,
                verbose_name='account type',
            ),
        ),
        migrations.AlterField(
            model_name='storegroup',
            name='agreementOnFile',
            field=models.BooleanField(default=False, verbose_name='agreement on file'),
        ),
        migrations.AlterField(
            model_name='storegroup',
            name='crossrefEnabled',
            field=models.BooleanField(default=False, verbose_name='Crossref enabled'),
        ),
        migrations.AlterField(
            model_name='storegroup',
            name='organizationAcronym',
            field=models.CharField(blank=True, max_length=255, verbose_name='acronym'),
        ),
        migrations.AlterField(
            model_name='storegroup',
            name='organizationName',
            field=models.CharField(
                max_length=255,
                validators=[ezidapp.models.validation.nonEmpty],
                verbose_name='name',
            ),
        ),
        migrations.AlterField(
            model_name='storegroup',
            name='organizationStreetAddress',
            field=models.CharField(
                max_length=255,
                validators=[ezidapp.models.validation.nonEmpty],
                verbose_name='street address',
            ),
        ),
        migrations.AlterField(
            model_name='storegroup',
            name='organizationUrl',
            field=models.URLField(max_length=255, verbose_name='URL'),
        ),
        migrations.AlterField(
            model_name='storeidentifier',
            name='agentRole',
            field=models.CharField(
                blank=True,
                choices=[('U', 'user'), ('G', 'group')],
                default='',
                max_length=1,
            ),
        ),
        migrations.AlterField(
            model_name='storeidentifier',
            name='createTime',
            field=models.IntegerField(
                blank=True,
                default='',
                validators=[django.core.validators.MinValueValidator(0)],
            ),
        ),
        migrations.AlterField(
            model_name='storeidentifier',
            name='crossrefMessage',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='storeidentifier',
            name='crossrefStatus',
            field=models.CharField(
                blank=True,
                choices=[
                    ('R', 'awaiting status change to public'),
                    ('B', 'registration in progress'),
                    ('S', 'successfully registered'),
                    ('W', 'registered with warning'),
                    ('F', 'registration failure'),
                ],
                default='',
                max_length=1,
            ),
        ),
        migrations.AlterField(
            model_name='storeidentifier',
            name='status',
            field=models.CharField(
                choices=[('R', 'reserved'), ('P', 'public'), ('U', 'unavailable')],
                default='P',
                max_length=1,
            ),
        ),
        migrations.AlterField(
            model_name='storeidentifier',
            name='target',
            field=models.URLField(
                blank=True,
                default='',
                max_length=2000,
                validators=[ezidapp.models.validation.unicodeBmpOnly],
            ),
        ),
        migrations.AlterField(
            model_name='storeidentifier',
            name='unavailableReason',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='storeidentifier',
            name='updateTime',
            field=models.IntegerField(
                blank=True,
                default='',
                validators=[django.core.validators.MinValueValidator(0)],
            ),
        ),
        migrations.AlterField(
            model_name='storeuser',
            name='accountEmail',
            field=models.EmailField(
                help_text='The email address to which account-related notifications are sent other than Crossref notifications.',
                max_length=255,
                verbose_name='account email',
            ),
        ),
        migrations.AlterField(
            model_name='storeuser',
            name='crossrefEmail',
            field=models.EmailField(
                blank=True, max_length=255, verbose_name='Crossref email'
            ),
        ),
        migrations.AlterField(
            model_name='storeuser',
            name='crossrefEnabled',
            field=models.BooleanField(default=False, verbose_name='Crossref enabled'),
        ),
        migrations.AlterField(
            model_name='storeuser',
            name='displayName',
            field=models.CharField(
                max_length=255,
                validators=[ezidapp.models.validation.nonEmpty],
                verbose_name='display name',
            ),
        ),
        migrations.AlterField(
            model_name='storeuser',
            name='inheritGroupShoulders',
            field=models.BooleanField(
                default=False,
                help_text='If checked, the user has access to all group shoulders; if not checked, the user has access only to the shoulders explicitly selected below.',
                verbose_name='inherit group shoulders',
            ),
        ),
        migrations.AlterField(
            model_name='storeuser',
            name='isGroupAdministrator',
            field=models.BooleanField(
                default=False, verbose_name='group administrator'
            ),
        ),
        migrations.AlterField(
            model_name='storeuser',
            name='isRealmAdministrator',
            field=models.BooleanField(
                default=False, verbose_name='realm administrator'
            ),
        ),
        migrations.AlterField(
            model_name='storeuser',
            name='isSuperuser',
            field=models.BooleanField(default=False, verbose_name='superuser'),
        ),
        migrations.AlterField(
            model_name='storeuser',
            name='loginEnabled',
            field=models.BooleanField(default=True, verbose_name='login enabled'),
        ),
        migrations.AlterField(
            model_name='storeuser',
            name='password',
            field=models.CharField(
                blank=True, max_length=128, verbose_name='set password'
            ),
        ),
        migrations.AlterField(
            model_name='storeuser',
            name='primaryContactEmail',
            field=models.EmailField(max_length=255, verbose_name='email'),
        ),
        migrations.AlterField(
            model_name='storeuser',
            name='primaryContactName',
            field=models.CharField(
                max_length=255,
                validators=[ezidapp.models.validation.nonEmpty],
                verbose_name='name',
            ),
        ),
        migrations.AlterField(
            model_name='storeuser',
            name='primaryContactPhone',
            field=models.CharField(
                max_length=255,
                validators=[ezidapp.models.validation.nonEmpty],
                verbose_name='phone',
            ),
        ),
        migrations.AlterField(
            model_name='storeuser',
            name='proxies',
            field=models.ManyToManyField(
                blank=True,
                help_text='A proxy is another user that may act on behalf of this user.',
                to='ezidapp.StoreUser',
            ),
        ),
        migrations.AlterField(
            model_name='storeuser',
            name='secondaryContactEmail',
            field=models.EmailField(blank=True, max_length=255, verbose_name='email'),
        ),
        migrations.AlterField(
            model_name='storeuser',
            name='secondaryContactName',
            field=models.CharField(blank=True, max_length=255, verbose_name='name'),
        ),
        migrations.AlterField(
            model_name='storeuser',
            name='secondaryContactPhone',
            field=models.CharField(blank=True, max_length=255, verbose_name='phone'),
        ),
        migrations.AlterField(
            model_name='updatequeue',
            name='enqueueTime',
            field=models.IntegerField(
                blank=True,
                default='',
                validators=[django.core.validators.MinValueValidator(0)],
            ),
        ),
        migrations.AlterField(
            model_name='updatequeue',
            name='operation',
            field=models.CharField(
                choices=[('C', 'create'), ('U', 'update'), ('D', 'delete')],
                max_length=1,
            ),
        ),
    ]
