# Generated by Django 3.1.7 on 2021-04-11 12:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ezidapp', '0027_auto_20210224_0522'),
    ]

    operations = [
        migrations.AlterField(
            model_name='searchidentifier',
            name='isTest',
            field=models.BooleanField(blank=True, editable=False),
        ),
        migrations.AlterField(
            model_name='storeidentifier',
            name='isTest',
            field=models.BooleanField(blank=True, editable=False),
        ),
    ]
