# Generated by Django 3.1.7 on 2021-03-24 15:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ezidapp', '0028_auto_20210323_1157'),
    ]

    operations = [
        migrations.DeleteModel(
            name='LinkChecker',
        ),
        # migrations.DeleteModel(
        #     name='ServerVariables',
        # ),
    ]
