# Generated by Django 3.1.7 on 2021-03-24 17:00

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ezidapp', '0029_auto_20210324_1531'),
    ]

    operations = [
        migrations.CreateModel(
            name='LinkChecker',
            fields=[
                (
                    'id',
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name='ID',
                    ),
                ),
                ('identifier', models.CharField(max_length=255, unique=True)),
                ('owner_id', models.IntegerField(db_index=True)),
                ('target', models.URLField(max_length=2000)),
                (
                    'lastCheckTime',
                    models.IntegerField(
                        default=0,
                        validators=[django.core.validators.MinValueValidator(0)],
                    ),
                ),
                (
                    'numFailures',
                    models.IntegerField(
                        db_index=True,
                        default=0,
                        validators=[django.core.validators.MinValueValidator(0)],
                    ),
                ),
                ('isBad', models.BooleanField(default=False, editable=False)),
                ('returnCode', models.IntegerField(blank=True, null=True)),
                ('error', models.TextField(blank=True)),
                ('mimeType', models.CharField(blank=True, max_length=255)),
                (
                    'size',
                    models.IntegerField(
                        blank=True,
                        null=True,
                        validators=[django.core.validators.MinValueValidator(0)],
                    ),
                ),
                ('hash', models.CharField(blank=True, max_length=32)),
            ],
            options={
                'index_together': {('owner_id', 'isBad', 'lastCheckTime')},
            },
        ),
    ]
