# Generated by Django 3.1.7 on 2021-04-11 12:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ezidapp', '0030_linkchecker'),
        ('ezidapp', '0028_auto_20210411_1216'),
    ]

    operations = []
