# Generated by Django 3.1.7 on 2021-04-13 04:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ezidapp', '0031_merge_20210411_1231'),
    ]

    operations = [
        # migrations.DeleteModel(
        #     name='BinderQueue',
        # ),
        # migrations.DeleteModel(
        #     name='CrossrefQueue',
        # ),
        # migrations.DeleteModel(
        #     name='DataciteQueue',
        # ),
        # migrations.DeleteModel(
        #     name='LinkChecker',
        # ),
        # migrations.DeleteModel(
        #     name='ServerVariables',
        # ),
    ]
