#! /usr/bin/env python

# Deletes all session cookies for a given user.  Usage:
#
# Usage: delete-sessions username
#
# This script requires several EZID modules.  The PYTHONPATH
# environment variable must include the .../SITE_ROOT/PROJECT_ROOT
# directory; if it doesn't, we attempt to dynamically locate it and
# add it.  The DJANGO_SETTINGS_MODULE environment variable must be
# set.
#
# Greg Janee <gjanee@ucop.edu>
# September 2015

import os.path
import sys

# The following must precede any EZID module imports:
execfile(os.path.join(os.path.split(os.path.abspath(__file__))[0],
  "offline.py"))

import django_util

if len(sys.argv) != 2:
  sys.stderr.write("Usage: delete-sessions username\n")
  sys.exit(1)

n = django_util.deleteSessions(sys.argv[1])
print "%d session%s deleted" % (n, "s" if n != 1 else "")
