#! /usr/bin/env python

# DataCite Metadata Store (MDS) administration tool.  Currently
# supports creating and viewing datacenters only.  Run with no
# arguments for usage.  Operations require the password associated
# with the datacenter's allocator.
#
# Caution: creating and updating a datacenter are the same operation.
# If it is creation that is really desired, check first that the
# datacenter does not already exist.
#
# Greg Janee <gjanee@ucop.edu>
# September 2012

import lxml.etree
import re
import sys
import urllib2
import xml.sax.saxutils

URL = "https://mds.datacite.org/datacentre"
CONTACT_NAME = "EZID Support Desk"
CONTACT_EMAIL = "ezid@ucop.edu"

class MyHTTPErrorProcessor (urllib2.HTTPErrorProcessor):
  def http_response (self, request, response):
    # Bizarre that Python leaves this out.
    if response.code == 201:
      return response
    else:
      return urllib2.HTTPErrorProcessor.http_response(self, request, response)
  https_response = http_response

# Defined here, but set below.
opener = None

usageText = """Usage: mdsadmin password operation...

  operation:
    c[reate] allocator.datacenter name prefixes...
    v[iew] allocator.datacenter

  operation examples:
    create FOO.BAR 'The FuBar Institute' 10.1234 10.5678
    view FOO.BAR
"""

def usageError ():
  sys.stderr.write(usageText)
  sys.exit(1)

def validateSymbol (symbol):
  m = re.match("([A-Z][-A-Z0-9]{0,6}[A-Z0-9])\.([A-Z][-A-Z0-9]{0,6}[A-Z0-9])$",
    symbol, re.I)
  if m:
    return (m.group(1).upper(), m.group(2).upper())
  else:
    sys.stderr.write("mdsadmin: invalid datacenter symbol\n")
    sys.exit(1)

def validatePrefix (prefix):
  if re.match("10\.\d{4,5}$", prefix):
    return prefix
  else:
    sys.stderr.write("mdsadmin: invalid prefix: %s\n" % prefix)
    sys.exit(1)

def nodeText (node):
  if node.text is not None:
    return node.text.strip()
  else:
    return ""

def xpathText (node, path, separator=""):
  return separator.join(nodeText(n) for n in node.xpath(path))

def formatDatacenter (record):
  root = lxml.etree.XML(record)
  o = []
  def format (label, path, separator=""):
    o.append("%s: %s" % (label, xpathText(root, path, separator)))
  format("symbol", "symbol")
  format("name" ,"name")
  format("contact name", "contactName")
  format("contact email", "contactEmail")
  format("DOI quota allowed", "doiQuotaAllowed")
  format("DOI quota used", "doiQuotaUsed")
  format("is active", "isActive")
  format("domains", "domains")
  format("comments", "comments")
  format("prefixes", "prefixes/prefix", ", ")
  format("updated", "updated")
  format("created", "created")
  return "\n".join(o)

def viewDatacenter (allocator, datacenter):
  try:
    c = opener.open(urllib2.Request("%s?symbol=%s.%s" % (URL, allocator,
      datacenter)))
    record = c.read()
    c.close()
  except urllib2.HTTPError, e:
    if e.fp != None:
      s = e.fp.read()
      if not s.endswith("\n"): s += "\n"
    else:
      s = ""
    sys.stderr.write("%d %s\n%s" % (e.code, e.msg, s))
    sys.exit(1)
  except Exception, e:
    sys.stderr.write("mdsadmin: %s\n" % str(e))
    sys.exit(1)
  print formatDatacenter(record),

createTemplate = """<?xml version="1.0"?>
<datacentre>
  <contactEmail>%s</contactEmail>
  <contactName>%s</contactName>
  <doiQuotaAllowed>-1</doiQuotaAllowed>
  <domains>*</domains>
  <isActive>true</isActive>
  <name>%%s</name>
%%s  <symbol>%%s.%%s</symbol>
</datacentre>
""" % (CONTACT_EMAIL, CONTACT_NAME)

def createDatacenter (allocator, datacenter, name, prefixes):
  request = urllib2.Request(URL)
  request.add_header("Content-Type", "application/xml; charset=UTF-8")
  request.add_data(createTemplate % (xml.sax.saxutils.escape(name),
    "".join("  <prefixes><prefix>%s</prefix></prefixes>\n" % p\
    for p in prefixes), allocator, datacenter))
  request.get_method = lambda: "PUT"
  try:
    c = opener.open(request)
    record = c.read()
    c.close()
  except urllib2.HTTPError, e:
    if e.fp != None:
      s = e.fp.read()
      if not s.endswith("\n"): s += "\n"
    else:
      s = ""
    sys.stderr.write("%d %s\n%s" % (e.code, e.msg, s))
    sys.exit(1)
  except Exception, e:
    sys.stderr.write("mdsadmin: %s\n" % str(e))
    sys.exit(1)
  print "Create/update successful, datacenter record follows..."
  print
  print formatDatacenter(record),

if len(sys.argv) < 4: usageError()

operation = filter(lambda o: o.startswith(sys.argv[2]), ["create", "view"])
if len(operation) != 1: usageError()

allocator, datacenter = validateSymbol(sys.argv[3])

opener = urllib2.build_opener(MyHTTPErrorProcessor())
h = urllib2.HTTPBasicAuthHandler()
h.add_password("mds.datacite.org", URL, allocator, sys.argv[1])
opener.add_handler(h)

if operation[0] == "view":
  if len(sys.argv) != 4: usageError()
  viewDatacenter(allocator, datacenter)
elif operation[0] == "create":
  if len(sys.argv) < 6: usageError()
  createDatacenter(allocator, datacenter, sys.argv[4],
    [validatePrefix(p) for p in sys.argv[5:]])
else:
  usageError()
