#! /usr/bin/env python

# Performs the second of three steps in populating the search database
# from a raw dump file.  This script does the main work of populating
# the identifier table.  Usage:
#
#    populate-search-2 < DUMP
#
# This script requires several EZID modules.  The PYTHONPATH
# environment variable must include the .../SITE_ROOT/PROJECT_ROOT
# directory; if it doesn't, we attempt to dynamically locate it and
# add it.  The DJANGO_SETTINGS_MODULE environment variable must be
# set.
#
# Greg Janee <gjanee@ucop.edu>
# November 2015

import os.path
import sys

# The following must precede any EZID module imports:
execfile(os.path.join(os.path.split(os.path.abspath(__file__))[0],
  "offline.py"))

import ezidapp.models.search_identifier
import util

for line in sys.stdin:
  id, record = util.fromExchange(line, identifierEmbedded=True)
  if "_s" in record:
    id = record["_s"]
  else:
    id = "ark:/" + id
  if record["_o"] != "anonymous":
    try:
      ezidapp.models.search_identifier.updateFromLegacy(id, record,
        forceInsert=True)
    except Exception, e:
      sys.stderr.write("Exception processing '%s': %s\n" % (id,
        util.oneLine(str(e))))
