#! /bin/bash

# Reloads and tests all EZID instances.
#
# Greg Janee <gjanee@ucop.edu>
# December 2011

# @executable

if [ $# -ne 1 ]; then echo "usage: $0 password"; exit 1; fi

CLIENT=`dirname $0`/client

METADATA="datacite.title test datacite.creator test datacite.publisher\
 test datacite.publicationyear test"

for server in staging production
do
  echo
  echo -n "Reload $server server? [y/n] "
  read yesno
  if [ "$yesno" == "y" ]; then
    echo Reloading...
    $CLIENT ${server:0:1} admin:"$1" reload
    if [ $? -eq 0 ]
    then
      echo Testing...
      $CLIENT ${server:0:1} admin:"$1" m ark:/99999/fk4
      $CLIENT ${server:0:1} admin:"$1" m doi:10.5072/FK2 $METADATA
    fi
  fi
done
