#! /bin/bash

# Runs the striplog tool on dated (i.e., already rolled over)
# transaction logs, appends the resulting records to the master
# historical transaction log, and deletes the dated transaction logs.
# The latter steps are performed only after a sanity check is
# performed and user confirmation.
#
# Greg Janee <gjanee@ucop.edu>
# January 2012

shopt -s nullglob

STRIPLOG=`dirname $0`/striplog
LOGDIR=`dirname $0`/../../logs
HISTDIR=$LOGDIR/historical
HISTLOG=$HISTDIR/master_transaction_log.gz

files=(${LOGDIR}/transaction_log.*)
if [ ${#files[@]} -eq 0 ]; then
  echo run-striplog: no transaction logs to process
  exit
fi

$STRIPLOG ${files[@]} | sort | gzip > $HISTDIR/new.gz
gzcat $HISTLOG $HISTDIR/new.gz | gzip > $HISTDIR/combined.gz

mrc=`gzcat $HISTLOG | wc -l`
nrc=`gzcat $HISTDIR/new.gz | wc -l`
crc=`gzcat $HISTDIR/combined.gz | wc -l`
if [ $((mrc+nrc)) -ne $crc ]; then
  echo run-striplog: record count sanity check failed
  exit 1
fi

echo -n "Replace master log and delete dated transaction logs? [y/n] "
read yesno
if [ "$yesno" == "y" ]; then
  mv $HISTDIR/combined.gz $HISTLOG
  rm ${files[@]} $HISTDIR/new.gz
fi
