# Generated by Django 3.2.18 on 2023-08-09 11:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ezidapp', '0002_auto_20221026_1139'),
    ]

    operations = [
        migrations.AlterField(
            model_name='binderqueue',
            name='status',
            field=models.CharField(choices=[('U', 'Awaiting submission'), ('C', 'Submitted, unchecked'), ('S', 'Submitted'), ('W', 'Registered with warning'), ('F', 'Registration failed'), ('T', 'Registration attempt unsuccessful'), ('I', 'Ignored (operation not applicable)'), ('O', 'Completed successfully')], db_index=True, default='U', max_length=1),
        ),
        migrations.AlterField(
            model_name='crossrefqueue',
            name='status',
            field=models.CharField(choices=[('U', 'Awaiting submission'), ('C', 'Submitted, unchecked'), ('S', 'Submitted'), ('W', 'Registered with warning'), ('F', 'Registration failed'), ('T', 'Registration attempt unsuccessful'), ('I', 'Ignored (operation not applicable)'), ('O', 'Completed successfully')], db_index=True, default='U', max_length=1),
        ),
        migrations.AlterField(
            model_name='datacitequeue',
            name='status',
            field=models.CharField(choices=[('U', 'Awaiting submission'), ('C', 'Submitted, unchecked'), ('S', 'Submitted'), ('W', 'Registered with warning'), ('F', 'Registration failed'), ('T', 'Registration attempt unsuccessful'), ('I', 'Ignored (operation not applicable)'), ('O', 'Completed successfully')], db_index=True, default='U', max_length=1),
        ),
        migrations.AlterField(
            model_name='searchindexerqueue',
            name='status',
            field=models.CharField(choices=[('U', 'Awaiting submission'), ('C', 'Submitted, unchecked'), ('S', 'Submitted'), ('W', 'Registered with warning'), ('F', 'Registration failed'), ('T', 'Registration attempt unsuccessful'), ('I', 'Ignored (operation not applicable)'), ('O', 'Completed successfully')], db_index=True, default='U', max_length=1),
        ),
    ]
