name: EZID CI
on: push

jobs:
  tests:
    runs-on: ubuntu-latest

    env:
      IS_CI: 1
      DJANGO_SETTINGS_MODULE: settings.tests

    steps:
      - uses: actions/checkout@v1

      - name: Set up MySQL
        run: |
          sudo /etc/init.d/mysql start
          mysql -h127.0.0.1 -uroot -proot -e 'create database if not exists ezid_test_db;'

#      - name: Install packaged deps
#        run: |
#          sudo apt-get install --yes libdb5.3-dev
#
#      - name: Prepare Python env
#        run: |
#          pip install --upgrade pip setuptools wheel
#          pip install -r ./requirements-dev.txt
#
##      - name: Dump environment
##        env:
##          PYTHONPATH: ${{ env.GITHUB_WORKSPACE }}
##        run: |
##          printf 'PYTHONPATH: %s\n' "$PYTHONPATH"
##          apt-cache pkgnames | sort
##          find / | grep /bin/ | sort
##          pip freeze
##          pip check || true
##          ls -l
##          python --version
##          ls -la ${HOME}
##          ls -la ${TRAVIS_BUILD_DIR}
##          echo "CWD=${PWD}"
##          mysql -e '
##            use ezid_test_db;
##            show tables;
##            select prefix, minter from ezidapp_shoulder;
##          '
#
##      - name: Prepare database
##        run: |
##          mysql -e "
##            create database if not exists ezid_test_db;
##            use ezid_test_db;
##            create user 'ezid_test_user'@'%' identified by '';
##            grant all privileges on *.* to 'ezid_test_user'@'%';
##            flush privileges;
##          "
##
#
##      - name: Prepare fixtures
##        run:
##          mkdir -p ../download/public ../logs
##          python ${TRAVIS_BUILD_DIR}/manage.py makemigrations --merge --no-input
##          python ${TRAVIS_BUILD_DIR}/manage.py migrate
##          python ${TRAVIS_BUILD_DIR}/manage.py collectstatic --no-input
##
##          python ${TRAVIS_BUILD_DIR}/manage.py loaddata --ignorenonexistent store-test
##          python ${TRAVIS_BUILD_DIR}/manage.py loaddata --ignorenonexistent search-init
##          python ${TRAVIS_BUILD_DIR}/manage.py loaddata --ignorenonexistent combined-limited
##
##          python ${TRAVIS_BUILD_DIR}/manage.py diag-update-admin
#
#
#      - name: Run tests
#        env:
#          PYTHONPATH: ${{ github.workspace }}
#        run: |
#          pytest --maxfail 10
#
##        - pip install -e .
